spring:
  port: 8080
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/fraud
    username: sa
    password:
    driverClassName: org.h2.Driver

fraud-detection-policy:
  maxMessageCount: 5
  numOfMinutes: 120
  pointsForRepeat: 100
  patterns:
    -
      pattern: "<a>"
      points: 1
    -
      pattern: "money|transfer|paypal"
      points: 10